### ISSUE TITLE
Push notification. Any one able to receive push notification when the app is in the background?

### ISSUE THREAD

**Issue by Kabangi** [ccm-innovation/react-native-twilio-chat#14]
I have configured my app with this module for push notification but when the app is in the "dead" mode no push notification is coming in.

Help or thoughts will be much appreciated.

**Comment by mattshen** [comment]
Push Notification is not covered much by this library.  There are still quite a list of configurations you'll need to do. 

Here is an article ([link](https://www.mattshen.com/2017/04/05/React-Native-Push-Notifications/)) I wrote about setting up push notification. Hope it would help. 

Also, you'll need to configure push notification in Twilio Console, basically putting push credentials there.

**Comment by Kabangi** [comment]
Thanks but I mean push notifications related to twilio. I have notifications already configured and working but am not receiving them from twilio on "dead" mode.

Works fine on foreground mode.

**Comment by mattshen** [comment]
are you on iOS?

**Comment by Kabangi** [comment]
Android

**Comment by Kabangi** [comment]
@mattshen After reading your article and one of the link in it I feel I have a better understanding of push notifications. Thanks a lot. I think my issue lies at the pushnotification lib am using ATM. Am using the first one. Will try to switch to the second one that you recommended maybe it will work. 

Thanks once again.

**Comment by bradbyte** [comment]
Thanks @mattshen for following up.. you're right, we're assuming an existing understand of RN Push Notifications exists outside of this library. Best of luck @Kabangi !
