### ISSUE TITLE
iOS setup failure

### ISSUE THREAD

**Issue by Ashvala** [ccm-innovation/react-native-twilio-chat#23]
I'm currently developing a React Native app with the intent of integrating twilio chat in. My current blocker is the setup process as I'm unfamiliar with pods, having been a long time carthage user.

Precursor to the problem: 

I followed instructions from [here](https://github.com/ccm-innovation/react-native-twilio-chat/blob/c0a78e6eb40c3c905514479d832307016c711891/README.md#ios---manually) in order to setup the project. 

I created a podfile in the iOS React Native project which looks like so: 

```
  pod 'TwilioChatClient', '~> 0.17.1'
  pod 'TwilioAccessManager', '~> 0.1.3'
```

Following which, I ran `pod install` and got the them linked in the xcworkspace. 

I added the library in my xcworkspace and linked it all up in the linking phase. 

However, running `react-native run-ios` or using the xcode run button yields the following error from the build process - it comes from the Check Pods Manifest.lock step

```
diff: /Users/ashvala/Projects/testproj/node_modules/react-native-twilio-chat/ios/../../ios/Pods/../Podfile.lock: No such file or directory
diff: /Users/ashvala/Projects/testproj/node_modules/react-native-twilio-chat/ios/../../ios/Pods/Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

Any insights into what could be happening here?

**Comment by bradbyte** [comment]
@Ashvala thanks for reaching out. When you say added the library, do you mean this repo? you can add this to the podfile and it should link it automatically.

**Comment by Ashvala** [comment]
Yes, this library. I manually linked it via the instructions I linked above. I will try the pods approach and see how that works out.

**Comment by Ashvala** [comment]
Alright, it worked out. The modified podfile looks like: 
```
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native'
  pod 'RCTTwilioChat', :path => '../node_modules/react-native-twilio-chat/ios'
  pod 'TwilioChatClient', '~> 0.17.1'
  pod 'TwilioAccessManager', '~> 0.1.3'
```

Worth mentioning that React Native 0.42+ requires an explicit include of Yoga. This might be worth noting in the readme for future reference. Thanks once again for taking the time to help! Appreciate it.

**Comment by bradbyte** [comment]
Glad you got it working! Those instructions were not part of the master branch. There is currently work being done to simplify that install and also support for RN `>0.40.0`. Best of luck!
