### ISSUE TITLE
iOS TwilioChatClient/TCHUserInfo.h not found

### ISSUE THREAD

**Issue by digitaldavenyc** [ccm-innovation/react-native-twilio-chat#34]
I'm trying to get up and running with react-native-twilio-chat on IOS and getting an error when trying to build the project. `Lexical or Preprocessor Issue: TwilioChatClient/TCHUserInfo.h not found`

I am using react-native 0.44 and have setup the TwilioSDK manually (I am not using CocoaPods). I tried running `react-native link react-native-twilio-chat` and it said it linked the library successfully and there were no errors installing the SDK itself, it wasn't until I added `react-native-twilio-chat` that it threw an error on building.

Any suggestions on what the issue is would be very helpful.

**Comment by digitaldavenyc** [comment]
This is related to Issue #9

**Comment by zachrnolan** [comment]
@digitaldavenyc What did you end up doing to get past this error? It still looks like #9 hasn't been fixed/merged back into this project.
