### ISSUE TITLE
Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by apengstrom** [ccm-innovation/react-native-twilio-chat#41]
I am getting "Cannot read property 'Constants' of undefined" from the Constants.js file in this application. It appears it cannot find the TwilioChatClient object. If I change line 22 to NativeModules.Constants, it does not err out my application.

react-native-cli: 2.0.1
react-native: 0.51.0

**Comment by apengstrom** [comment]
Turns out the Pods were not installed properly, the TwilioAccessClient was non-existent.

**Comment by sahil-innostax** [comment]
@apengstrom can you brief the steps to resolve this issue.i am getting the same error.Using RN 0.47.2

**Comment by apengstrom** [comment]
I updated my podfile and installed the pods as per various documentation I found spread across the internet. Major PITA to be honest. I can't accurately remember the locations of the information I found, but I can provide you with a copy of what my Podfile looks like.

**Comment by apengstrom** [comment]
# Uncomment the next line to define a global platform for your project
# NOTE: The underlying Twilio SDKs require a minimum deployment target of 8.1
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/twilio/cocoapod-specs'

target 'AppNameHere' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Import required Lib from react-native
  # https://facebook.github.io/react-native/docs/integration-with-existing-apps.html#podfile
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'BatchedBridge', # Fix for [#15049](https://github.com/facebook/react-native/issues/15049)
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTText',
    'RCTSettings',
    'RCTVibration',
    'RCTWebSocket'
  ]

  # Pods for AppNameHere
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'RCTTwilioChat', :path => '../node_modules/react-native-twilio-chat/ios'
  pod 'TwilioChatClient', '~> 2.1.0'
  pod 'TwilioAccessManager', '~> 1.0.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end

**Comment by apengstrom** [comment]
[Podfile.txt](https://github.com/ccm-innovation/react-native-twilio-chat/files/1692245/Podfile.txt)

**Comment by apengstrom** [comment]
Just FYI that post installer script is because when running with Pods, for some reason React ends up in there twice. It was causing errors so I researched a way to remove the second React lib.

**Comment by sahil-innostax** [comment]
Thanks @apengstrom
